name: Swap functional tests

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
  pull_request:

jobs:
  job_functional_tests:
    uses: mavryk-network/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@develop
    with:
      branch_for_exchange: 'develop'
      branch_for_mavryk: ${{ github.repository }}
      test_filter: '"mavryk"'
